[package]
name = "particle-system"
version = "0.1.0"
edition = "2024"

[package.metadata.wasm-pack.profile.release] 
wasm-opt = ["-O", "--enable-bulk-memory"]

[profile.release]
strip = true

[dependencies]
anyhow = "1.0.102"
bytemuck = "1.25.0"
egui = "0.35.0"
egui-wgpu = "0.35.0"
egui-winit = {version = "0.35.0", features = ["android-native-activity", "links", "wayland", "x11"], default-features = false}
env_logger = "0.11.10"
log = "0.4.33"
pollster = "0.4.0"
web-time = "1.1.0"
wgpu = "29.0.3"
winit = {version = "0.30.13", features = ["android-native-activity"]}

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
wgpu = { version = "29.0.3" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
]}

